@layout_page_id=45c76935-b531-41e2-8994-7e309bee7ca5

@header_block_id=c5321fbf-c849-4233-a667-9c02bf7146fa

GET http://localhost:{{$dotenv PORT}}/blocks

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "create",
      "payload": {
        "blockVariant": "header1",
        "wrapperContained": true,
        "blockContained": true,
        "textLogo": "toranjMedia",
        "textLogoProps": {"color": "blue"},
        "textLogoClassName": "sample-class-name"
        
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "patch",
      "patchActionUpdates": "BLOCK_ONLY",
      "payload": {
        "blockId": "{{header_block_id}}",
        # "blockVariant": "header1",
        # "blockType": "na na na",
        # "isLtr": true,
        # "blockStyle": {"backgroundColor": "#03A9F4"},
        # "textLogo": "Salamat Trading",
        # "slogan": "Your Trusted Broker",
        # "textLogoProps": {"color": "green"},
        "sloganProps": {"backgroundColor": "aqua", "padding": ".7rem", "borderRadius":"0.5rem"}
      }
    }
  ]
}


###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "delete",
      "payload": {
        "blockId": "{{header_block_id}}"
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "fetch",
      "payload": {
        "blockId": "{{header_block_id}}"
        # "blockId": "dcfe0b23-ee06-4d66-90ab-444c49781a90"
      }
    }
  ]
}