@layout_page_id=bff3ee33-31ca-40d2-953a-9dddf5764886
@home_page_id=650e7134-61af-42d4-a953-e3eb30cb26ca

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "add",
      "payload": {
        "blockType": "header",
        "blockVariant": "header1",
        "isActive": true,
        "wrapperContained": false,
        "blockContained": true,
        "blockOptions": {
        "textLogo": "test is here",
        "textLogoClassName": "there is no class",
        "textLogoStyle": { "color":"red" }
      }
        },
        "order": 1,
        "sag": 2
      }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "hero",
      "action": "delete",
      "payload": {
        "id": "sample-hero-block-id"
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "hero",
      "action": "update",
      "payload": {
        "id": "sample-hero-block-id"
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "create",
      "payload": {
        "blockVariant": "header1",
        "isActive": true,
        "wrapperContained": true,
        "blockContained": true,
        "order": 2,
        "textLogo": "toranjMedia",
        "textLogoStyle": {"color": "red"},
        "textLogoClassName": "sample-class-name"
        
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "patch",
      "payload": {
        "blockVariant": "header2",       
        "wrapperContained": true,
        "textLogoClassName": "sample-class-name"
      }
    }
  ]
}


###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "delete",
      "payload": {
        "blockId": "{{layout_page_id}}"
      }
    }
  ]
}