@layout_page_id=209a129f-342d-4ecb-b80a-8aa6f61e5030

@header_block_id=db6e194c-a66d-4ca0-be85-60e6a1b0c155

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "create",
      "payload": {
        "blockVariant": "header1",
        "wrapperContained": true,
        "blockContained": true,
        "textLogo": "toranjMedia",
        "textLogoProps": {"color": "blue"},
        "textLogoClassName": "sample-class-name"
        
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "patch",
      "patchActionUpdates": "BOTH",
      "payload": {
        "blockId": "{{header_block_id}}",
        # "blockVariant": "header1",
        # "blockType": "na na na",
        "isLtr": false,
        # "blockStyle": {"backgroundColor": "silver"},
        # "textLogo": "Salamat Trading II"
        # "slogan": "Your Trusted Broker",
        "textLogoProps": {"color": "green"}
      }
    }
  ]
}


###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "delete",
      "payload": {
        "blockId": "{{header_block_id}}"
      }
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/blocks
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "webpageId": "{{layout_page_id}}",
  "actions": [
    {
      "resource": "header",
      "action": "fetch",
      "payload": {
        "blockId": "{{header_block_id}}"
        # "blockId": "dcfe0b23-ee06-4d66-90ab-444c49781a90"
      }
    }
  ]
}