
@layout_page_id=bff3ee33-31ca-40d2-953a-9dddf5764886

GET http://localhost:{{$dotenv PORT}}/menu/{{layout_page_id}}/HEADER_PRIMARY

###

POST http://localhost:{{$dotenv PORT}}/menu
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "menuType":"HEADER_PRIMARY",
  "title": "Header Menu",
  "items": [
    {
      "title": "Home",
      "url": "/home",
      "isFeatured": false
    },
    {
      "title": "About",
      "url": "/about"
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/menu
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "menuType":"FOOTER_PRIMARY",
  "title": "Footer Menu",
  "items": [
    {
      "title": "Home",
      "url": "/home",
      "isFeatured": false
    },
    {
      "title": "About",
      "url": "/about"
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/menu
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "menuType":"FOOTER_SECONDARY",
  "title": "Footer Social Menu",
  "items": [
    {
      "icon": "youtube",
      "url": "https://www.youtube.com/@salamattrading"
    },
    {
      "icon": "telegram",
      "url": "https://t.me/g9giGirCfg5hZjg8"
    }
  ]
}
