@layout_page_id=bff3ee33-31ca-40d2-953a-9dddf5764886


GET http://localhost:{{$dotenv PORT}}/profile/{{layout_page_id}}
Webpage-Id: {{layout_page_id}}

###

POST http://localhost:{{$dotenv PORT}}/profile
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "title": "Salamat Trading",
  "headerLogo": {
    "imageLogoUrl": "https://yt3.ggpht.com/qd-3PVa5gu4Q8I4980JqdTIh2Di6P4aDi30dc2ZqQ1VzTXkdE6EG0rHST0ww8QkZiI8vwgDM=s176-c-k-c0x00ffffff-no-rj-mo"
  },
  "footerLogo": {
    "textLogo": "Salamat Trading"
  }
}