@handle=salamat-trading

GET http://localhost:{{$dotenv PORT}}/websites
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

POST http://localhost:{{$dotenv PORT}}/websites
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "handle": "mrbeast",
  "title": "Mr Beast",
  "description": "Mr Beast"
  # "themeCode": "my-theme",
  # "layoutVariant": "heem2",
  # "isRtl": true
}

###

POST http://localhost:{{$dotenv PORT}}/websites/new-website-for-youtube-channel
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "handle": "mrbeast",
  "title": "Mr Beast",
  "description": "Mr Beast",
  "youtubeHandle": "mrbeast"
  # "themeCode": "my-theme",
  # "layoutVariant": "heem2",
  # "isRtl": true
}

