@handle=salamat-trading

GET http://localhost:{{$dotenv PORT}}/websites
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

POST http://localhost:{{$dotenv PORT}}/websites
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "handle": "salamat-trading",
  "title": "Salamat Trading Broker",
  "description": "Your Trusted Crypto Broker"
  # "themeCode": "my-theme",
  # "layoutVariant": "heem2",
  # "isRtl": true
}

