@handle=salamat-trading
@home_page=home
@bio_page=bio

@layout_page_id=8bf871ca-539e-4d13-96bd-0c41a0b8a4dc

### MENU

GET http://localhost:{{$dotenv PORT}}/menu/{{layout_page_id}}/HEADER_PRIMARY

###

POST http://localhost:{{$dotenv PORT}}/menu
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "menuType":"HEADER_PRIMARY",
  "title": "Header Menu",
  "items": [
    {
      "title": "Home",
      "url": "/home",
      "isFeatured": false
    },
    {
      "title": "About",
      "url": "/about"
    }
  ]
}

###

POST http://localhost:{{$dotenv PORT}}/menu
Content-Type: application/json

{
  "webpageId": "{{layout_page_id}}",
  "menuType":"FOOTER_PRIMARY",
  "title": "Footer Menu",
  "items": [
    {
      "title": "Home",
      "url": "/home",
      "isFeatured": false
    },
    {
      "title": "About",
      "url": "/about"
    }
  ]
}

### PAGES
GET http://localhost:{{$dotenv PORT}}/websites/{{handle}}/pages/{{home_page}}

###

GET http://localhost:{{$dotenv PORT}}/websites/{{handle}}/pages/{{bio_page}}

###

POST http://localhost:{{$dotenv PORT}}/websites/{{handle}}/pages
Content-Type: application/json

{
  "pageType":"HOME",
  "pageVariant": "home1",
  "title": "Home",
  "slug": "home"
}

###

POST http://localhost:{{$dotenv PORT}}/websites/{{handle}}/pages
Content-Type: application/json

{
  "pageType":"BIO",
  "pageVariant": "bio1",
  "title": "Bio",
  "slug": "bio",
  "layoutOverrides": {
    "dir": "rtl",
    "header": {"isActive": false},
    "footer": {"isActive": false}
  }
}

### WEBSITES

POST http://localhost:{{$dotenv PORT}}/websites
Content-Type: application/json

{
  "handle": "salamat-trading",
  "themeCode": "heem"
}

### DATA

POST http://localhost:{{$dotenv PORT}}/websites/{{handle}}/sync
Content-Type: application/json

{
  "youtubeHandle": "salamattrading"
}