export const RESOURCE_OR_ACTION_NOT_SUPPORTED =
  'RESOURCE_OR_ACTION_NOT_SUPPORTED';
export const ALREADY_EXIST = 'ALREADY_EXIST';
export const LAYOUT_NOT_FOUND = 'LAYOUT_NOT_FOUND';
export const WEBSITE_NOT_FOUND = 'WEBSITE_NOT_FOUND';
export const WEBPAGE_NOT_FOUND = 'WEBPAGE_NOT_FOUND';
export const WEBPAGE_ID_NOT_PROVIDED = 'WEBPAGE_ID_NOT_PROVIDED';
export const BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND';
export const BAD_REQUEST = 'BAD_REQUEST';
export const INVALID_BLOCK_VARIANT = 'INVALID_BLOCK_VARIANT';
export const SERVER_ERROR = 'SERVER_ERROR';
