export const RESOURCE_OR_ACTION_NOT_SUPPORTED =
  'RESOURCE_OR_ACTION_NOT_SUPPORTED';

export const LAYOUT_NOT_FOUND = 'LAYOUT_NOT_FOUND';
export const WEBSITE_NOT_FOUND = 'WEBSITE_NOT_FOUND';
export const WEBPAGE_NOT_FOUND = 'WEBPAGE_NOT_FOUND';
export const BAD_REQUEST = 'BAD_REQUEST';
